apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: api-feed
  name: api-feed
spec:
  replicas: 2
  selector:
    matchLabels:
      service: api-feed
  template:
    metadata:
      labels:
        service: api-feed
    spec:
      containers:
      - image: genius3/udagram-api-feed:v1
        name: api-feed
        ports:
        - containerPort: 8080
        imagePullPolicy: Always
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "2048Mi"
            cpu: "500m"                  
        envFrom:
          - secretRef:
              name: env-secret
              optional: false
          - configMapRef:
              name: env-configmap
              optional: false      
        volumeMounts:
        - name: aws-secret
          mountPath: "/root/.aws"
          readOnly: true
      volumes:
      - name: aws-secret
        secret:
          secretName: aws-secret