language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-frontend ./udagram-frontend
  - docker build -t udagram-reverseproxy ./udagram-reverseproxy

  - docker tag udagram-api-feed genius3/udagram-api-feed:latest
  - docker tag udagram-api-user genius3/udagram-api-user:latest
  - docker tag udagram-frontend genius3/udagram-frontend:latest
  - docker tag udagram-reverseproxy genius3/udagram-reverseproxy:latest

# Tasks to perform after the process is successful. Formatting the Docker username and password as below enables you to programmatically log in without having the password exposed in logs.
after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

  - docker push genius3/udagram-api-feed:latest
  - docker push genius3/udagram-api-user:latest
  - docker push genius3/udagram-frontend:latest
  - docker push genius3/udagram-reverseproxy:latest