apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: api-user
  name: api-user
spec:
  replicas: 2
  selector:
    matchLabels:
      service: api-user
  template:
    metadata:
      labels:
        service: api-user
    spec:
      containers:
      - image: genius3/udagram-api-user:v1
        name: api-user
        ports:
        - containerPort: 8080 
        imagePullPolicy: Always  
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "2048Mi"
            cpu: "500m"     
        envFrom:
          - secretRef:
              name: env-secret
              optional: false
          - configMapRef:
              name: env-configmap
              optional: false