apiVersion: v1
kind: Service
metadata:
    labels:
        service: api-user
    name: api-user
spec:
    ports:
    - name: "8001"
      port: 8080
      targetPort: 8080
    selector:
        service: api-user